stages:
  - build
  - test
  - docker
  - deploy

variables:
  PYTHON_VERSION: "3.11"
  DOCKER_TLS_CERTDIR: ""

build_backend:
  stage: build
  image: python:3.9-slim
  script:
    - cd medisecure-backend
    - pip install -r requirements.txt
  artifacts:
    paths:
      - medisecure-backend/

test_backend:
  stage: test
  image: python:3.9-slim
  script:
    - cd medisecure-backend
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest --junitxml=tests/reports/junit.xml --cov=. --cov-report=xml:tests/reports/coverage.xml
  artifacts:
    when: always
    reports:
      junit: medisecure-backend/tests/reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: medisecure-backend/tests/reports/coverage.xml

docker_build:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest medisecure-backend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest -f medisecure-frontend/Dockerfile medisecure-frontend
    - docker push $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest

deploy:
  stage: deploy
  image: alpine:3.19
  before_script:
    - apk add --no-cache ansible openssh-client
  script:
    - ansible-playbook ansible/playbooks/deploy.yml -i ansible/inventories/prod/hosts.ini --extra-vars "backend_image=$CI_REGISTRY_IMAGE/backend:latest"
  when: manual
