groups:
  - name: backend_alerts
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le)) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          description: "Latency above 500ms for HTTP requests."

      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: "Backend API is not responding."
